version: 2
jobs:
  node:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
  ios:
      macos:
        xcode: "10.3"
steps:
      - checkout
      - run: npm install
      - run: npm test
workflows:
  version: 2
  node-ios:
    jobs:
      - node
      - ios:
          requires:
            - node  